CREATE TABLE IF NOT EXISTS `users`(
    `id` BIGINT(255) NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `level` BIGINT(255) DEFAULT 0 NOT NULL,
    `currentHealth` BIGINT(255) DEFAULT 20 NOT NULL,
    `maxHealth` BIGINT(255) DEFAULT 20 NOT NULL,
    `attack` BIGINT(255) DEFAULT NULL,
    `exp` BIGINT DEFAULT 0 NOT NULL,
    `equippedItem` VARCHAR(255) DEFAULT NULL,
    `location` VARCHAR(255) DEFAULT 'Knossos'
);

CREATE TABLE IF NOT EXISTS `inventory`(
    `id` BIGINT(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `quantity` BIGINT(255) NOT NULL DEFAULT 1,
    `mods` VARCHAR(255) DEFAULT NULL,
    `gold` BIGINT(255) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `tablets` (
    `id` BIGINT(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `user_name` VARCHAR(255) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `dateFound` DATE NOT NULL DEFAULT SYSDATE()
);